name: Deploy GitHub Pages
on:
  push:
    branches:
      # make sure this is the branch you are using
      - master
permissions:
  contents: write
jobs:
  bun:
    uses: ./.github/workflows/bun.yml # (1)
  deploy-gh-pages:
    needs: bun # (2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true
      - uses: actions/cache@v4
        id: bun-cache
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.local
          key: ${{ hashFiles('**/workflows/*.yml', '**/package*.json') }}
      - run: bun install -E
      - run: bun build-github-pages > .vuepress/dist/.nojekyll
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: .vuepress/dist
